### ISSUE TITLE
taxQuery not available in schema after activating plugin

### ISSUE THREAD

**Issue by fullsteamlabs** [wp-graphql/wp-graphql-tax-query#2]
Is this plugin still working? With both wp-graphql and wp-graphql-tax-query activated, taxQuery does not appear to be available in the schema. I have flushed permalinks as well.

**Comment by jasonbahl** [comment]
@fullsteamlabs thanks for reporting. There were some big changes to the WPGraphQL plugin since February (when this extension was created) and since we don't actively use this extension we haven't maintained compatibility with the core plugin. 

If you want to investigate and open a PR that would be sweet, otherwise I'll look into a fix soon (hopefully within a few days) and will also look into automating some unit tests to make sure it remains working for future versions of the wp-graphql plugin.

**Comment by fullsteamlabs** [comment]
Forked the repo, gave it a shot, looks like ya beat me to it! Thanks for that, it's working again! Even though I didn't quite get there. I'm feeling more familiar with the codebase after searching and fumbling around a bit. If there's anything we can help with in the future, happy to try!

**Comment by jasonbahl** [comment]
There's some issues labeled "help wanted" so if you're interested in working on one have at it! Leave a comment on the issue and I can change the status to "work in progress". And happy to chat in slack or in the issue comments to clarify anything you work on.

**Comment by DevOpsRadar** [comment]
Hey, @jasonbahl 
I experience the same issue. Installed and activated wp-graphql-tax-query 0.0.2 and wp-graphql 0.3.4 and nothing appear in schema...

**Comment by DevOpsRadar** [comment]
Ok, sorry I found what was the problem. I downloaded the zip from release, not a master branch. Now it works.

**Comment by jasonbahl** [comment]
@DevOpsRadar thanks for the follow up 😄

**Comment by DevOpsRadar** [comment]
@jasonbahl Is there any chance you can push this plugin and wp-graphql-meta-query to Composer?
